// default package
// Generated 09-jun-2015 15:56:59 by Hibernate Tools 3.4.0.CR1
package codegeneration;
/**
 * EmpDetailsView generated by hbm2java
 */
public class EmpDetailsView implements java.io.Serializable {

	private EmpDetailsViewId id;

	public EmpDetailsView() {
	}

	public EmpDetailsView(EmpDetailsViewId id) {
		this.id = id;
	}

	public EmpDetailsViewId getId() {
		return this.id;
	}

	public void setId(EmpDetailsViewId id) {
		this.id = id;
	}

}
